---
title: "Natalia Ciranova"
---
nataliaciranova@gmail.com



I am a postgraduate student in the University of Glasgow's [Institute of Neuroscience and Psychology](http://www.gla.ac.uk/researchinstitutes/neurosciencepsychology/). I am currently studying for the MSc Research methods of psychological science with my supervisor [Dr Esther Papies](https://www.gla.ac.uk/schools/psychology/staff/estherpapies/). My Master thesis is examining social influence as social norms and their effect on consumer choices in the context of food sustainability. 


###Research Interest

My research interest lays close to the topic of my current thesis within the context of sustainability and social influence. I am interested in the mechanisms of social norms and their potential long term effects on consumers' purchase choices.


###Education
#####2018 - present  	University of Glasgow, Scotland (MSc)
                  Currently studying for MSc Research Methods of Psychological Science, Thesis in the theme of food sustainability and normative pressure,                                         supervisor: Esther Papies

#####2015 - 2018 	  	Lancaster University, UK
                  BSc Hons Marketing with Psychology
                
#####2018		        	Lancaster Excellence Award, Lancaster University-]
                  Acknowledgement for extracurricular activities, development of new skills  and enhancement of employment prospects

#####2007 - 2015		    Gymnasium na Ulici Ladislava Saru (Maturita equivalent to A-levels)


### Research Experience

####Social Processes lab (2017-2018) 

Research assistant in a quantitative research on the topic of ethical food choices and animal welfare led by Dr Jared Piazza at Psychology department, Lancaster University



####Cognition of Social Interaction (CoSI) lab (2017-2018)

Research assistant in a research on the topic of perspective-taking and cognition led by Dr Jessica Wang at Psychology department, Lancaster University



####Consultancy Research Project (2017-2018)

Market Researcher: qualitative and quantitative research to identify solutions for decreasing demand of restaurant in Lancaster



####SUMAC Lab (2016-2017)

Research assistant in self-regulation, unconscious motivation, action control lab working alongside Dr Kathleen McCulloch on multiple experiments 	
